plugin: aws_ec2

aws_access_key: AKIAUBZL63AJQNLRYIHE
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
