plugin: aws_ec2

aws_access_key: AKIAUBZL63AJYOUG7O5V
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
